config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :user, controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :edit, :update ]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :areas, only: [:index, :create, :edit, :update, :destroy]
    resources :temperatures, only: [:index, :create, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
    end
    get '/users/check' => 'users#check'
    patch '/users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      member do
        get :favorites
        get :draft
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container-fluid">
  <div class="row mb-3">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h2 class="mt-4">管理ページ</h2>
    </div>
  </div>
  <div class="row align-content-center d-flex justify-content-center">
    <div class="col-12 col-md-6 shadow-lg">
      <div class="d-flex justify-content-center row mt-5">
        <div class="btn-wrapper col-md-4 mx-2">
          <li class="btn btn-outline-warning btn-sm btn-block mb-3 ">
            <%= link_to "ユーザー管理", admin_users_path, class: 'text-dark' %>
          </li>
          <li class="btn btn-outline-warning btn-sm btn-block mb-3 ">
            <%= link_to "投稿管理", admin_posts_path, class: 'text-dark' %>
          </li>
          <li class="btn btn-outline-warning btn-sm btn-block mb-3 ">
            <%= link_to "コメント管理", admin_comments_path, class: 'text-dark' %>
          </li>
          <li class="btn btn-outline-warning btn-sm btn-block mb-3 ">
            <%= link_to "地域", admin_areas_path, class: 'text-dark' %>
          </li>
          <li class="btn btn-outline-warning btn-sm btn-block mb-5 ">
            <%= link_to "気温", admin_temperatures_path, class: 'text-dark' %>
          </li>
        </div>
      </div>
    </div>
  </div>
</div>