config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :user, controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :edit, :update ]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :areas, only: [:index, :create, :edit, :update, :destroy]
    resources :temperatures, only: [:index, :create, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
    end
    get '/users/check' => 'users#check'
    patch '/users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      member do
        get :favorites
        get :draft
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  belongs_to :area, optional: true
  belongs_to :temperature, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search(keyword, area_name, temperature_name)
    @posts = Post.all
    if keyword.present?
      @posts = Post.where('text LIKE(?)', "%#{keyword}%")
    end
    if area_name.present?
      @posts = @posts.left_joins(:area).where(area:{area_name: area_name})
    end
    if temperature_name.present?
      @posts = @posts.left_joins(:temperature).where(temperature:{temperature_name: temperature_name})
    end
    @posts
  end
  
  def area_name
    if self.area_id.present?
      Area.find(self.area_id).area_name
    else
      "未選択"
    end
  end

  def temperature_name
    if self.temperature_id.present?
      Temperature.find(self.temperature_id).temperature_name
    else
      "未選択"
    end
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'dafault-imagZZe.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_cut_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'dafault-imagZZe.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_fill: [256, 170]).processed
  end


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  with_options presence: true, on: :publicize do
    validates :image
    validates :area
    validates :temperature
    validates :text
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.page(params[:page])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to admin_posts_path
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :text, :area_id, :temperature_id )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end
  
  def index
    @posts = Post.all
  end
  
  def search
    @posts = Post.search(params[:keyword], params[:area_id], params[:temperature_id])
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    favorites = Favorite.where(post_id: @post.id).pluck(:user_id)
    @favorite_users = User.find(favorites)
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user.id)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :text, :area_id, :temperature_id )
  end
  
  def is_matching_login_user
    post = Post.find(params[:id])
    unless post.user_id == current_user.id
      redirect_to posts_path
    end
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>投稿編集</h1>
<%= form_with model: @post do |f| %>
  <%= image_tag @post.get_image(200, 200) %>
　<h4>説明</h4>
  <%= f.text_field :text %>
  
  <%= f.submit '更新' %>
  <%= link_to "削除", post_path(@post.id), method: :delete %>
  
<% end %>

app/views/posts/index.html.erb
<h1>ALL</h1>
<%=link_to "新規投稿する", new_post_path %>

<%= form_with(url: search_posts_path, local: true, method: :get ) do |f| %>
  <%= f.text_field :keyword %>
  <%= f.select :area_name, options_from_collection_for_select( Area.all, :area_name, :area_name), {prompt: "選択してください"} %>
  <%= f.select :temperature_name, options_from_collection_for_select( Temperature.all, :temperature_name, :temperature_name), {prompt: "選択してください"} %>
  <%= f.submit "検索" %>
<% end %>



<% @posts.each do |post| %>
  <div>
    <%= link_to image_tag(post.get_image(200,200)), post_path(post.id) %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @post, url: posts_path do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  
  <h4>地域</h4>
  <%= f.select :area_id, options_from_collection_for_select(Area.all, :id, :area_name), { prompt: "選択してください" } %>

  <h4>気温</h4>
  <%= f.select :temperature_id, options_from_collection_for_select(Temperature.all, :id, :temperature_name), { prompt: "選択してください" } %>
  
  <h4>説明</h4>
  <%= f.text_field :text %>
  
  <%= f.submit '投稿' %>
<% end %>
  

  

app/views/posts/search.html.erb
検索画面

<% @posts.each do |post| %>
    <div>
      <%= image_tag post.get_image(200, 200) %>
      地域：<%= post.area_name %>
      気温<%= post.temperature_name %>
      説明：<%= post.text %>
      <%= link_to "詳細", post_path(post.id) %>
    </div>
<% end %>

app/views/posts/show.html.erb
<h1>詳細</h1>

  <%= image_tag @post.get_image(200, 200) %>
  <p>ユーザーネーム：<%= @post.user.name %></p>
  <p>地域：<%= @post.area_name %></p>
  <p>気温：<%= @post.temperature_name %></p>
  <p>説明：<%= @post.text %></p>
  <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
  
  <% if @post.user == current_user %>
    <%= link_to "編集", edit_post_path(@post.id) %>
  <% end %>
  
  <% if @post.favorited_by?(current_user) %>
    <p>
      <%= link_to post_favorite_path(@post), method: :delete do %>
        ♥<%= @post.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_favorite_path(@post), method: :post do %>
        ♡<%= @post.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  
  <% @favorite_users.each do |user| %>
  <div>
    <%= link_to image_tag(@user.get_profile_image(100,100)), user_path(user.id) %>
  </div>
  <% end %>

<div>
  <p>コメント件数：<%= @post.comments.count %></p>
  <% @post.comments.each do |comments| %>
    <p><%= image_tag comments.user.get_profile_image(100,100) %></p>
    <%= comments.user.name %>
    <%= comments.created_at.strftime('%Y/%m/%d') %><%= comments.comment %>
    <% if comments.user == current_user %>
      <%= link_to "削除", post_comment_path(comments.post, comments), method: :delete %>
    <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@post, @comment] do |f| %>
    <%= f.text_area :comment, placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>