config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :user, controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :edit, :update ]
    resources :posts, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :areas, only: [:index, :create, :edit, :update, :destroy]
    resources :temperatures, only: [:index, :create, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
    end
    get '/users/check' => 'users#check'
    patch '/users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      member do
        get :favorites
        get :draft
      end
    end

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nanikiru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/76f411fe92.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <!--<div class='fixed-top'>-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#72c6ef;">
          <div class="container-fluid">
            <li class="navbar-brand">
              <%= link_to "ナニキル", about_path, class: 'text-light' %>
            </li>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <div class="navbar-nav ms-auto">
                  <li class="nav-link">
                    <%= link_to "Myページ", user_path(current_user.id), class: 'text-light' %>
                  </li>
                  <li class="nav-link">
                    <%= link_to "ALL", posts_path, class: 'text-light' %>
                  </li>
                  <li class="nav-link">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-light' %>
                  </li>
                </div>
              <% elsif admin_signed_in? %>
                <div class="navbar-nav ms-auto">
                  <li class="nav-link">
                    <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: 'text-light' %>
                  </li>
                  <li class="nav-link">
                    <%= link_to "管理トップ", admin_path, class: 'text-light' %>
                  </li>
                </div>
              <% else %>
                <div class="navbar-nav ms-auto">
                  <li class="nav-link">
                    <%= link_to "TOP", root_path, class: 'text-light' %>
                  </li>
                  <li class="nav-link">
                    <%=link_to "新規登録",  new_user_registration_path, class: 'text-light' %>
                  </li>
                  <li class="nav-link">
                    <%=link_to "ログイン",  new_user_session_path, class: 'text-light' %>
                  </li>
                </div>
              <% end %>
            </div>
          </div>
        <!--</div>-->
      </nav>
    </header>
    <%= yield %>
  </body>
</html>